### PR TITLE
Add support for the Private API

### PR DESCRIPTION
**Pull request by joshporter1**
Addresses issue #11 by adding functionality to call the API endpoints for the [VirusTotal Private API](https://www.virustotal.com/en/documentation/private-api). 

* Adds additional methods for previously unsupported endpoints
* Modifies existing methods to support optional parameters that are used in the Private API
* Refactored some of the code to extract repeated functionality into the base class to allow for less repetition and better reusability

### CODE REVIEW

**Comment by joshporter1** [comment]
Any updates on the status of my pull request? If there's any issues let me know and I can resubmit. Thanks!

**Comment by hammackj** [comment]
Hey sorry, I will try to get this merged today just need to look over it.

**Comment by hammackj** [comment]
Could you send the PR against the dev branch please? I probably dont have it documented but easier for me to merge that way.

**Comment by joshporter1** [comment]
I just updated this PR to merge into the dev branch. Thanks for taking the time to look this over.

**Comment by hammackj** [comment]
Everything should be merged into dev now. If you find any issues please feel free to send more pull requests. I will push a new gem soon.

**Pull request merged**
